version: '2.0'

services:

  grabber:
    image: matrocob/grabber:1.0.2-SNAPSHOT
    restart: always
    ports:
      - 8080:8080
    links:
      - "postgres-grabber"
    depends_on:
      - postgres-grabber

  postgres-grabber:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432